version: "2"
linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck
run:
  timeout: 5m
  build-tags: []
issues:
  exclude-dirs:
    - bin
    - data
    - .data
